### ISSUE TITLE
Specify stroke width

### ISSUE THREAD

**Issue by futuretap** [davedelong/sfsymbols#1]
This is awesome since the SF Symbols app makes it hard to export.
I'd love to be able to specify the font weight or stroke width.

Thanks for your great little tool!

**Comment by davedelong** [comment]
Specifying the font weight would be cool... I'll poke around and see if I can come up with anything. However, since this repo was mainly a "I wonder if I can do that" project, I'm not making any promises about if or when 😄

**Comment by davedelong** [comment]
I just figured out (I think) how to do this. If my suspicions are correct, I'll put this in over the weekend.

**Comment by davedelong** [comment]
Fixed by 9831bb6
