### ISSUE TITLE
No files are output

### ISSUE THREAD

**Issue by Wevah** [davedelong/sfsymbols#14]
After building and symlinking to `/usr/local/bin`, running

`sfsymbols --output symbols --format png`

creates the `symbols` directory, but no files are written inside it.

I've got the SF Symbols app version 1.0 (13) installed, which I just downloaded today. Specifying the font path explicitly doesn't change anything.

Running 10.14.6 and Swift 5.1 (Xcode 11).

**Comment by davedelong** [comment]
My guess would be that it's not finding the font correctly, or somehow not able to load the glyphs properly.

I'm going to add a `--verbose` flag to the options, so it can be more chatty about what's going on, and hopefully that will help me diagnose the issue.

**Comment by Wevah** [comment]
I might take a look at this too if I find time.

**Comment by arvaki** [comment]
CSV table has been changed.
New columns:
`Additional Search Metadata,Categories,Glyph Order,NEW  PUAs,Non-modifiable,Protected Symbol Notes,RTL extension,semantic.name.1,semantic.name.2,semantic.name.3,short.name,unicodes`.
I fixed the issue in my [fork](https://github.com/kireev165/sfsymbols). Should I make a PR?

**Comment by davedelong** [comment]
Yes please!
