### ISSUE TITLE
Export PDF Iconsets as template images

### ISSUE THREAD

**Issue by owenzhao** [davedelong/sfsymbols#18]
All pdf image works great on light mode. But in dark mode, either image for image.fill looks too dark to use.

light mode
<img width="261" alt="light_mode" src="https://user-images.githubusercontent.com/2182896/70408718-1e9f8f00-1a84-11ea-827f-e589cddd7d59.png">

dark mode
<img width="261" alt="dark_mode" src="https://user-images.githubusercontent.com/2182896/70408717-1e06f880-1a84-11ea-9ed9-401deb15e750.png">

dark mode fill
<img width="261" alt="dark_mode_fill" src="https://user-images.githubusercontent.com/2182896/70408713-1e06f880-1a84-11ea-891d-dc69d51b7f75.png">

**Comment by owenzhao** [comment]
Changing fill color from black to white can provide dark mode images. I have update the project to provide both images in light and dark mode. However, I don't know how to send my revised code.

light mode
<img width="262" alt="light_mode_revised" src="https://user-images.githubusercontent.com/2182896/70427231-4fe18480-1aaf-11ea-8bd8-715948972a6c.png">

dark mode
<img width="262" alt="dark_mode_revised" src="https://user-images.githubusercontent.com/2182896/70427240-553ecf00-1aaf-11ea-8aa9-855d2bb73cb2.png">

**Comment by owenzhao** [comment]
I have managed to give you a pull. Maybe it helps.

**Comment by melgu** [comment]
You could also just invert it in code.
SwiftUI example:
```swift
Image("person.crop.circle.badge.plus")
    .colorInvert()
```

**Comment by owenzhao** [comment]
I have done the same result by changing the fill color. Thanks any way.

**Comment by melgu** [comment]
Fill color isn't available in SwiftUI (macOS), right?

**Comment by owenzhao** [comment]
> Fill color isn't available in SwiftUI (macOS), right?

I didn't change the code on my own project. Instead, I did it by revising the code of the talking project. And write both light images and dark images at the same time. So I could enjoy the benefit of Xcode assets.

<img width="641" alt="Xcode Image Assets" src="https://user-images.githubusercontent.com/2182896/70844890-af121100-1e82-11ea-88ce-2c7e3cb16466.png">

**Comment by arvaki** [comment]
I believe you should render the assets as template images instead.

**Comment by davedelong** [comment]
I'm repurposing this to track the "export as template images" work.

This should also apply to the other formats that exports as an iconset.

**Comment by davedelong** [comment]
Both PNGs and PDFs get marked as being template images when exported as part of asset catalogs. I just verified that they render correct in light and dark mode.
