### ISSUE TITLE
Does not build with swift 5.1.3 (included in Xcode 11.3.1) under Mojave

### ISSUE THREAD

**Issue by jschuster** [davedelong/sfsymbols#21]
swift build -c release

results in a Error Message:
Product 'SPMUtility' not found. It is required by target 'sfsymbols'

Will it only work with newer Xcode version?

**Comment by davedelong** [comment]
Ah, it should probably switch to using the new [ArgumentParser](https://github.com/apple/swift-argument-parser) package.

I'll maybe have time to make that change soon, but a PR would also be welcome.

**Comment by jschuster** [comment]
As a interims solution it helps to replace the line 15
 `.package(url: "https://github.com/apple/swift-package-manager.git", from: "0.4.0")`
with
`.package(url: "https://github.com/apple/swift-package-manager.git", .branch("swift-5.1-branch"))`

This branch provides SPMUtility and the compiling works.

**Comment by futuretap** [comment]
Thanks @jschuster, also helps with the current Xcode 11.4 (11E146) on Catalina.

**Comment by davedelong** [comment]
Thanks to #22, this now uses the ArgumentParser package.
