### ISSUE TITLE
Namespace generated Swift paths

### ISSUE THREAD

**Issue by colejd** [davedelong/sfsymbols#6]
Hello!

It'd be helpful if the Swift generator put each path as a named property of a parent class. Then it'd be a ready-to-go file to put in a project. Something like this:

```
class SymbolPath: UIBezierPath {
    // Override point for generated paths
}
class Symbols {
    static let someSymbolName: SymbolPath = {
        // Dump corresponding path here (the entirety of one of the swift files you're generating now) and return
    }
}
```

Thank you!

**Comment by colejd** [comment]
I'm wondering if maybe a dictionary would be a better way to go. That way there could be parity between the key and the string you'd pass to `UIImage(systemName:)` in iOS 13.

**Comment by davedelong** [comment]
The current bezierPath generation will generate `static var ...` extensions on `UIBezierPath`, such as:

```swift
extension UIBezierPath {
    static var symbol00Circle: UIBezierPath { ... }
    static var symbol00CircleFill: UIBezierPath { ... }
    ...
}
```
